name: $(date:yyyyMMdd)$(rev:-r)

trigger: none

stages:
- stage: Deploy_Resources
  variables:
    - template: ../StDemo/Parameters/Parameters.yml
    - template: ../StDemo/Parameters/BaseParameters.yml

  jobs:
  - deployment: Deploy_Resources

    pool:
      vmImage: 'windows-latest'

    environment: 'poc'
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self 

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy Resource Group
            inputs:
              deploymentScope: 'Subscription'
              azureResourceManagerConnection: '${{variables.azure_connection_name}}'
              subscriptionId: '$(subscriptionid)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/StDemo/ResourceTemplates/ResourceGroup.json'
              overrideParameters: '-rgName $(rg_name) -rgLocation $(location)'
              deploymentMode: 'Incremental'

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy MySQL DB
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '${{variables.azure_connection_name}}'
              resourceGroupName: '$(rg_name)'
              subscriptionId: '$(subscriptionid)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/StDemo/ResourceTemplates/MySqlDB.json'
              overrideParameters: '-serverName $(server_name) -administratorLogin $(administrator_login) -administratorLoginPassword $(administrator_login_password) -skuCapacity $(sku_capacity) -skuName $(sku_name) -SkuSizeMB $(sku_size_mb) -SkuTier $(sku_tier) -skuFamily $(sku_family) -mysqlVersion $(mysql_version) -location $(location) -backupRetentionDays $(backup_retention_days) -geoRedundantBackup $(geo_redundant_backup) -workspaceName $(workspace_name) -workspaceRgName $(workspace_rg_name)'
              deploymentMode: 'Incremental'

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy App Service plan
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '${{variables.azure_connection_name}}'
              resourceGroupName: '$(rg_name)'
              subscriptionId: '$(subscriptionid)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/StDemo/ResourceTemplates/AppServicePlan.json'
              overrideParameters: '-appServicePlanName $(app_service_plan_name) -location $(location) -sku $(sku) -minimumCapacity $(minimum_capacity) -maximumCapacity $(maximum_capacity) -defaultCapacity $(default_capacity) -metricName $(metric_name) -metricThresholdToScaleOut $(metric_threshold_to_scaleout) -metricThresholdToScaleIn $(metric_threshold_to_scalein) -changeCountScaleOut $(change_count_scaleout) -changeCountScaleIn $(change_count_scalein) -autoscaleEnabled $(autoscale_enabled)'
              deploymentMode: 'Incremental'

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy Web App
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '${{variables.azure_connection_name}}'
              resourceGroupName: '$(rg_name)'
              subscriptionId: '$(subscriptionid)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/StDemo/ResourceTemplates/WebApp.json'
              overrideParameters: '-webAppName $(web_app_name) -appServicePlanName $(app_service_plan_name) -location $(location) -language $(language) -workspaceName $(workspace_name) -workspaceRgName $(workspace_rg_name)'
              deploymentMode: 'Incremental'

          - task: MysqlDeploymentOnMachineGroup@1
            displayName: Create DB in Mysql
            inputs:
              TaskNameSelector: 'InlineSqlTask'
              SqlInline: 'CREATE DATABASE stdemo;'
              ServerName: 'stdemo-sql.mysql.database.azure.com'
              SqlUsername: 'stadmin@stdemo-sql'
              SqlPassword: '$(administrator_login_password)'

          

- stage: Build_WordPress
  variables:
    - template: ../StDemo/Parameters/Parameters.yml
    - template: ../StDemo/Parameters/BaseParameters.yml

  jobs:
  - deployment: Build_Deploy_WordPress

    pool:
      name: Hosted Ubuntu 1604
      demands: node.js

    environment: 'poc'
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self 

          - task: ArchiveFiles@2
            displayName: 'Archive build files'
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/StDemo/WordPress'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

          - task: AzurePowerShell@4
            displayName: Prod to Staging
            inputs:
              azureSubscription: '${{variables.azure_connection_name}}'
              ScriptType: 'FilePath'
              ScriptPath: '$(Build.SourcesDirectory)/StDemo/Scripts/ProdToStage.ps1'
              ScriptArguments: '-WebAppName $(web_app_name)'
              errorActionPreference: 'continue'
              azurePowerShellVersion: 'latestVersion'

          - task: AzureRmWebAppDeployment@4
            displayName: Deploy the WordPress
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'AzureSub'
              appType: 'webApp'
              WebAppName: '$(web_app_name)'
              deployToSlotOrASE: true
              ResourceGroupName: '$(rg_name)'
              SlotName: 'staging'
              packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'
              enableCustomDeployment: true
              DeploymentType: 'zipDeploy'

          - task: AzureAppServiceManage@0
            displayName: Switch the slot
            inputs:
              azureSubscription: 'AzureSub'
              Action: 'Swap Slots'
              WebAppName: '$(web_app_name)'
              ResourceGroupName: '$(rg_name)'
              SourceSlot: 'staging'
