name: $(date:yyyyMMdd)$(rev:-r)

trigger: none

stages:
- stage: Deploy_Resources
  variables:
    - template: ./Parameters/Parameters.yml
    - template: ./Parameters/BaseParameters.yml

  jobs:
  - deployment: Deploy_Resources

    pool:
      vmImage: 'windows-latest'

    environment: 'poc'
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self 

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy Primary Resource Group
            inputs:
              deploymentScope: 'Subscription'
              azureResourceManagerConnection: '${{variables.azure_connection_name}}'
              subscriptionId: '$(subscriptionid)'
              location: '$(pri_location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/ResourceTemplates/ResourceGroup.json'
              overrideParameters: '-rgName $(pri_rg_name) -rgLocation $(pri_location)'
              deploymentMode: 'Incremental'

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy MySQL DB
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '${{variables.azure_connection_name}}'
              resourceGroupName: '$(pri_rg_name)'
              subscriptionId: '$(subscriptionid)'
              location: '$(pri_location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/ResourceTemplates/MySqlDB.json'
              overrideParameters: '-serverName $(server_name) -administratorLogin $(administrator_login) -administratorLoginPassword $(administrator_login_password) -skuCapacity $(sku_capacity) -skuName $(sku_name) -SkuSizeMB $(sku_size_mb) -SkuTier $(sku_tier) -skuFamily $(sku_family) -mysqlVersion $(mysql_version) -location $(pri_location) -backupRetentionDays $(backup_retention_days) -geoRedundantBackup $(geo_redundant_backup) -workspaceName $(workspace_name) -workspaceRgName $(workspace_rg_name)'
              deploymentMode: 'Incremental'

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy Primary App Service plan
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '${{variables.azure_connection_name}}'
              resourceGroupName: '$(pri_rg_name)'
              subscriptionId: '$(subscriptionid)'
              location: '$(pri_location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/ResourceTemplates/AppServicePlan.json'
              overrideParameters: '-appServicePlanName $(pri_app_service_plan_name) -location $(pri_location) -sku $(sku) -minimumCapacity $(minimum_capacity) -maximumCapacity $(maximum_capacity) -defaultCapacity $(default_capacity) -metricName $(metric_name) -metricThresholdToScaleOut $(metric_threshold_to_scaleout) -metricThresholdToScaleIn $(metric_threshold_to_scalein) -changeCountScaleOut $(change_count_scaleout) -changeCountScaleIn $(change_count_scalein) -autoscaleEnabled $(autoscale_enabled)'
              deploymentMode: 'Incremental'

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy Primary Web App
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '${{variables.azure_connection_name}}'
              resourceGroupName: '$(pri_rg_name)'
              subscriptionId: '$(subscriptionid)'
              location: '$(pri_location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/ResourceTemplates/WebApp.json'
              overrideParameters: '-webAppName $(pri_web_app_name) -appServicePlanName $(pri_app_service_plan_name) -location $(pri_location) -language $(language) -appInsightsName $(app_insights_name) -workspaceName $(workspace_name) -workspaceRgName $(workspace_rg_name)'
              deploymentMode: 'Incremental'

          - task: MysqlDeploymentOnMachineGroup@1
            displayName: Create DB in Mysql
            inputs:
              TaskNameSelector: 'InlineSqlTask'
              SqlInline: 'CREATE DATABASE IF NOT EXISTS stdemo;'
              ServerName: '$(mysqlsrvname)'
              SqlUsername: '$(mysqluser)'
              SqlPassword: '$(administrator_login_password)'

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy Trafic Manager
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '${{variables.azure_connection_name}}'
              resourceGroupName: '$(pri_rg_name)'
              subscriptionId: '$(subscriptionid)'
              location: '$(pri_location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/ResourceTemplates/TraficManager.json'
              overrideParameters: '-trafficManagerName $(traffic_manager_name) -uniqueDnsNameForWebApp $(pri_web_app_name) -uniqueDnsName $(unique_dns_name)'
              deploymentMode: 'Incremental'

          

- stage: Build_WordPress
  variables:
    - template: ./Parameters/Parameters.yml
    - template: ./Parameters/BaseParameters.yml

  jobs:
  - deployment: Build_Deploy_WordPress

    pool:
      name: Hosted Ubuntu 1604
      demands: node.js

    environment: 'poc'
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self 

          - task: ArchiveFiles@2
            displayName: 'Archive build files'
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/WordPress'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

          - task: AzurePowerShell@4
            displayName: Prod to Staging primary
            inputs:
              azureSubscription: '${{variables.azure_connection_name}}'
              ScriptType: 'FilePath'
              ScriptPath: '$(Build.SourcesDirectory)/Scripts/ProdToStage.ps1'
              ScriptArguments: '-WebAppName $(pri_web_app_name)'
              errorActionPreference: 'continue'
              azurePowerShellVersion: 'latestVersion'

          - task: AzureRmWebAppDeployment@4
            displayName: Deploy the WordPress primary
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'AzureSub'
              appType: 'webApp'
              WebAppName: '$(pri_web_app_name)'
              deployToSlotOrASE: true
              ResourceGroupName: '$(pri_rg_name)'
              SlotName: 'staging'
              packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'
              enableCustomDeployment: true
              DeploymentType: 'zipDeploy'

          - task: AzureAppServiceManage@0
            displayName: Switch the slot primary
            inputs:
              azureSubscription: 'AzureSub'
              Action: 'Swap Slots'
              WebAppName: '$(pri_web_app_name)'
              ResourceGroupName: '$(pri_rg_name)'
              SourceSlot: 'staging'

