variables:

# Resource Group parameters
- name: rg_name
  value: 'stdemo-rg'
# MySql DB parameters
- name: server_name
  value: 'stdemo-sql'
- name: administrator_login
  value: 'stadmin'
- name: sku_capacity
  value: 2
- name: sku_name
  value: GP_Gen5_2
- name: sku_size_mb
  value: 5120
- name: sku_tier
  value: GeneralPurpose
- name: sku_family
  value: Gen5
- name: mysql_version
  value: '5.7'
- name: backup_retention_days
  value: 7
- name: geo_redundant_backup
  value: 'Disabled'
# App Service plan parameters
- name: app_service_plan_name
  value: 'stdemo_plan'
- name: sku
  value: S1
- name: minimum_capacity
  value: 2
- name: maximum_capacity
  value: 5
- name: default_capacity
  value: 2
- name: metric_name
  value: CpuPercentage
- name: metric_threshold_to_scaleout
  value: 70
- name: metric_threshold_to_scalein
  value: 20
- name: change_count_scaleout
  value: 1
- name: change_count_scalein
  value: 1
- name: autoscale_enabled
  value: true
# Web App parameters
- name: web_app_name
  value: 'stdemowebapp'
- name: language
  value: php
