variables:

# Resource Group parameters
- name: pri_rg_name
  value: 'stdemo-rg-primary'
- name: sec_rg_name
  value: 'stdemo-rg-secondary'
- name: fd_rg_name
  value: 'stdemo-rg-frontdoor'
# MySql DB parameters
- name: server_name
  value: 'stdemo-sqlsrv'
- name: administrator_login
  value: 'stadmin'
- name: sku_capacity
  value: 2
- name: sku_name
  value: GP_Gen5_2
- name: sku_size_mb
  value: 5120
- name: sku_tier
  value: GeneralPurpose
- name: sku_family
  value: Gen5
- name: mysql_version
  value: '5.7'
- name: backup_retention_days
  value: 7
- name: geo_redundant_backup
  value: 'Disabled'
# App Service plan parameters
- name: pri_app_service_plan_name
  value: 'stdemo_plan_primary'
- name: sec_app_service_plan_name
  value: 'stdemo_plan_Secondary'
- name: sku
  value: S1
- name: minimum_capacity
  value: 2
- name: maximum_capacity
  value: 5
- name: default_capacity
  value: 2
- name: metric_name
  value: CpuPercentage
- name: metric_threshold_to_scaleout
  value: 70
- name: metric_threshold_to_scalein
  value: 20
- name: change_count_scaleout
  value: 1
- name: change_count_scalein
  value: 1
- name: autoscale_enabled
  value: true
# Web App parameters
- name: pri_web_app_name
  value: 'stdemowebappprimary'
- name: sec_web_app_name
  value: 'stdemowebappsecondary'
- name: language
  value: php
- name: app_insights_name
  value: stdemoappi
# Additional Parameters
- name: mysqlsrvname
  value: $(server_name).mysql.database.azure.com
- name: mysqluser
  value: stadmin@$(server_name)
# Trafic Manager parameters
- name: traffic_manager_name
  value: stdemotr
- name: unique_dns_name
  value: stdemosite