variables:

# general parameters
- name: azure_connection_name
  value: 'AzureSub'
- name: environmentName
  value: poc2
- name: subscriptionid
  value: f0108bad-f761-4ad8-84a9-5e514dfd1eea
# Resource Group parameters
- name: rg_name
  value: 'poc-rg13'
- name:  location
  value: 'westeurope'